// 按需全局引入 vant组件
import Vue from 'vue'
import {
  Calendar,
  Grid,
  GridItem,
  Loading,
  Tabbar,
  TabbarItem,
  List,
  Button,
  Popup,
  Form,
  Field,
  NumberKeyboard,
  Tab,
  Tabs,
  Dialog,
  ImagePreview,
  Cell,
  CellGroup,
  Lazyload,
  Picker,
  ActionSheet,
  PullRefresh,
  Checkbox,
  CheckboxGroup,
  Uploader,
  DatetimePicker,
  Swipe,
  SwipeItem,
  Tag,
  Divider,
  Overlay,
  Rate,
  Search,
  RadioGroup,
  Radio,
  Progress,
  NoticeBar,
  Icon,
  Stepper,
  Image,
  Empty,
  Slider,
  Cascader
} from 'vant'

Vue.use(Cascader)
Vue.use(Slider)
Vue.use(Empty)
Vue.use(Image)
Vue.use(Stepper)
Vue.use(Progress)
Vue.use(Overlay)
Vue.use(Divider)
Vue.use(Calendar)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Loading)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(List)
Vue.use(Button)
Vue.use(Popup)
Vue.use(Form)
Vue.use(Field)
Vue.use(NumberKeyboard)
Vue.use(Tab)
Vue.use(Tabs)
Vue.use(Dialog)
Vue.use(ImagePreview)
Vue.use(Cell)
Vue.use(CellGroup)
Vue.use(Loading)
Vue.use(Lazyload)
Vue.use(Tag)
Vue.use(Rate)
Vue.use(Search)
Vue.use(NoticeBar)
Vue.use(Icon)
Vue.use(Picker)
Vue.use(ActionSheet)
Vue.use(PullRefresh)
Vue.use(Checkbox)
Vue.use(CheckboxGroup)
Vue.use(Uploader)
Vue.use(DatetimePicker)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Radio)
Vue.use(RadioGroup)
